services:
  backend:
    restart: always
    build: BACKEND-fastAPI/
    volumes:
        - C:\Users\Yehor\Documents\Habit Tracker\BACKEND-fastAPI:/back_app
    ports:
      - "8000:8000"

  frontend:
    restart: always
    build: frontend-react-app/
    volumes:
      - C:\Users\Yehor\Documents\Habit Tracker\frontend-react-app:/front_app
    ports:
      - "3000:3000"