services:
  backend:
    restart: always
    build: BACKEND-fastAPI/
    volumes:
        - ./BACKEND-fastAPI/database.db:/back_app/database.db
    ports:
      - "8000:8000"

  frontend:
    restart: always
    build: frontend-react-app/
    ports:
      - "3000:3000"